work_dir: /mnt/netdisk/zhangjh/Code/PCM_extend/distill_checkpoints/no_infonce/best_pcm/xsub/detection
weights: /mnt/netdisk/zhangjh/Code/PCM_extend/distill_checkpoints/no_infonce/best_pcm/xsub/checkpoint_0150.pth.tar
ignore_weights: [clip_queue,shuffle_decoder,mp_prompt,base_prompt,cl_prompt,mix_prompt,mask_prompt,recons_prompt,maskgen,linear,recons_decoder,mask_param,classifier,encoder_q.fc, encoder_k, queue,encoder_q_motion,encoder_q_bone,encoder_r,encoder_l,Queue,]
rename_weights:
- encoder_k.encoder_q
#start_epoch: 0
#start_iter: 38200
# feeder
# feeder

train_feeder: feeder.ntu_feeder_detect.Feeder_single_sliding_window
train_feeder_args:
    data_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/train_data.npy
    input_size: 64
    l_ratio:
    - 0.5
    - 1.0
    label_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/train_label.npy
    start_pos_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/train_start_list.txt
    video_name_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/train_video_name.txt
    num_frame_path: /mnt/netdisk/linlilang/SkeletonContrast/data/NTU-RGB-D-60-AGCN/xsub/train_num_frame.npy
 
test_feeder: feeder.ntu_feeder_detect.Feeder_single
test_feeder_args:
    data_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/val_data.npy
    input_size: 64
    l_ratio:
    - 0.95
    label_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/val_label.npy
    start_pos_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/val_start_list.txt
    video_name_path: /mnt/netdisk/zhangjh/data/PKU1_Detection/untrimmed/val_video_name.txt
    num_frame_path: /mnt/netdisk/linlilang/SkeletonContrast/data/NTU-RGB-D-60-AGCN/xsub/train_num_frame.npy


# model
model: net.detection_baseline.GRU_Detect
model_args:
  hidden_size: 1024
  num_class: 53

#optim
weight_decay: 0.0
base_lr: 0.01
warm_up_epoch: 0
optimizer: SGD
step: [50, 70]
# training
device: [0]
batch_size: 64
test_batch_size: 1
num_epoch: 20

save_interval: -1
eval_interval: 5


